mutation mark_verification_sent(
  $id: ID!
  $email_verification_sent_at: String!
  $email_verification_sent_count: Int!
) {
  record: record_update(
    id: $id
    record: {
      table: "modules/user/profile"
      properties: [
        { name: "email_verification_sent_at", value: $email_verification_sent_at }
        { name: "email_verification_sent_count", value_int: $email_verification_sent_count }
      ]
    }
  ) {
    id
    email_verification_sent_at: property(name: "email_verification_sent_at")
    email_verification_sent_count: property_int(name: "email_verification_sent_count")
  }
}
