query (
  $channel: String!
  $since: String
  $limit: Int!
  $order: SortOrderEnum!
) {
  records(
    per_page: $limit
    page: 1
    filter: {
      table: { value: "modules/sse/sse_event" }
      properties: [{ name: "channel", value: $channel }]
      created_at: { gt: $since }
    }
    sort: [{ created_at: { order: $order } }]
  ) {
    total_entries
    results {
      id
      created_at
      channel: property(name: "channel")
      event: property(name: "event")
      data: property(name: "data")
    }
  }
}
